version: '3'

volumes:
  budget_app_mysql_data:
    driver: local

services:
  mysql:
    image: mysql:5.7
    volumes:
      - budget_app_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: budget_app_api_mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
        - 6603:3608
